### ISSUE TITLE
Practicing raising an issue - Add contact info like Nostr 

### ISSUE THREAD

**Issue by therealsupermax** [jesuspirate/jet#1]
I'm practicing creating issues on repo's; thought yours would be a great place to start for me. 

What do you think about adding your Nostr npub on your github somewhere? Or would you like to keep things separated? I added mine here in my README, but trying to make it a hyperlink.

https://github.com/therealsupermax/therealsupermax/blob/main/README.md

**Comment by jesuspirate** [comment]
This is fantastic idea! Some people even add their resume here, removing any PIIs (address, phone number..) and focusing on the PoW. I'm not there _yet_ hahahaha

**Comment by therealsupermax** [comment]
Brilliant! I'm not there yet either lmao.
Btw I did find out how to make my npub a hyperlink using this Github Markdown guide here

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

**Comment by jesuspirate** [comment]
Yup! :D I love it!! LFG
